config/routes.rb
Rails.application.routes.draw do
  resources :chats, except: [:edit, :update]
  resources :testbooks
  resources :mains
  resources :prefectures
  resources :aria
  resources :schools
  resources :students
  devise_for :teachers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'teachers', to: 'teachers#index'
  get 'teachers/:id', to: 'teachers#show'
  patch "teacher/:id", to: "teachers#authentication", as: "teacher"
  post "search_teacher", to: "tops#search_teacher"
  post "ask_approve", to: "tops#ask_approve"
  get "update_grade", to: "tops#update_grade"
  get "chats/new/:teacher_id", to: "chats#new"

  # Defines the root path route ("/")
  # root "articles#index"
  root 'tops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/arium.rb
class Arium < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :teacher

end

app/models/flow.rb
class Flow < ApplicationRecord

  belongs_to :main

end

app/models/homework.rb
class Homework < ApplicationRecord

  validates :main_id, uniqueness: { scope: :textbook_id }

  belongs_to :main
  belongs_to :textbook, class_name: "Testbook"

end

app/models/main.rb
class Main < ApplicationRecord

  belongs_to :student

  has_many :flows, dependent: :destroy
  accepts_nested_attributes_for :flows, reject_if: proc {|attributes| attributes['content'].blank?}, allow_destroy: true
  
  has_many :main_textbooks, dependent: :destroy
  accepts_nested_attributes_for :main_textbooks, reject_if: proc {|attributes| attributes['textbook_id'].blank?}, allow_destroy: true

  has_many :homeworks, dependent: :destroy
  accepts_nested_attributes_for :homeworks, reject_if: proc {|attributes| attributes['textbook_id'].blank?}, allow_destroy: true

  def textbooks_hash
    ret = {}
    self.main_textbooks.each do |mt|
      t = Testbook.find_by(id: mt.textbook_id)
      ret[t.id] = {id: mt.id, name: t.name, finished_place: mt.finished_place} if t
    end
    return ret
  end
  
  def homeworks_hash
    ret = {}
    self.homeworks.each do |h|
      t = Testbook.find_by(id: h.textbook_id)
      ret[t.id] = {id: h.id, name: t.name, amount: h.amount} if t
    end
    return ret
  end

  def student
    unless self.student_id.blank?
      return Student.find(self.student_id)
    else
      return Student.find(session[:student_id]) if session[:student_id]
    end
    return nil
  end

  def textbook_ids
    arr = []
    self.main_textbooks.each do |mt|
      arr.push(mt.textbook_id)
    end
    return arr
  end

  def homework_ids
    arr = []
    self.homeworks.each do |h|
      arr.push(h.textbook_id)
    end
    return arr
  end

end

app/models/main_textbook.rb
class MainTextbook < ApplicationRecord

  validates :main_id, uniqueness: { scope: :textbook_id }

  belongs_to :main
  belongs_to :textbook, class_name: "Testbook"

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  def hash_format
    return {id: self.id, name: self.name}
  end
  
end

app/models/school.rb
class School < ApplicationRecord
  
  validates :name, presence: :true
  validates :school_id, presence: :true
  validates :prefecture_id, presence: :true
  validates :name, uniqueness: true
  validates :school_id, uniqueness: :true

  def hash_format
    return {id: self.id, name: self.name}
  end
  
end

app/models/student.rb
class Student < ApplicationRecord

  validates :level, presence: :true
  validates :attitude, presence: :true
  has_many :mains, -> { order(updated_at: :desc) }

  def area
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    a = Arium.find_by(id: p.area_id) if p
    return a.id if a
  end

  def prefecture
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    return p.id if p
  end

  def school
    return School.find_by(id: self.school_id)
  end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :chats

  def area
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    a = Arium.find_by(id: p.area_id) if p
    return a.id if a
  end

  def prefecture
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    return p.id if p
  end

  def school
    return School.find_by(id: self.school_id)
  end

  def hash_format
    if self.school.blank?
      return {id: self.id, name: self.name, school: ""}
    else
      return {id: self.id, name: self.name, school: self.school.name}
    end
  end

end

app/models/testbook.rb
class Testbook < ApplicationRecord
  validates :name, uniqueness: true
  validates :name_kana, presence: :true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all.order(:name_hurigana)
  end

  # GET /students/1 or /students/1.json
  def show
    session[:student_id] = params[:id]
  end

  # GET /students/new
  def new
    @student = Student.new
    @student.grade = 9
    @student.school_id = current_teacher.school_id
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :name_hurigana, :grade, :personality, :attitude, :level, :school_id, :how_to_focus, :supplement, :goal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aria_helper.rb
module AriaHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/mains_helper.rb
module MainsHelper

  def subjects_options
    return {"国語" => 1, "算数・数学" => 2, "理科" => 3, "社会" => 4, "英語" => 5}
  end

end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def grades_options
    options = {}
    (1..6).each do |n|
      options = options.merge({"小学#{n}年" => n})
    end
    (7..9).each do |n|
      options = options.merge({"中学#{n-6}年" => n})
    end
    (10..12).each do |n|
      options = options.merge({"高校#{n-9}年" => n})
    end
    options = options.merge({"既卒" => 13})
    return options
  end

  def levels_options
    return {"かなり前の内容から復習が必要" => 1, "復習が必要" => 2, "学校の授業に合わせたらいい" => 3, "少し予習も取り入れている" => 4}
  end
  
  def attitudes_options
    return {"全然集中しない" => 1, "やる気にムラがある" => 2, "いつも集中している" => 3}
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/testbooks_helper.rb
module TestbooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "生徒の名前（例：虎居太郎[スペースは使わないこと]）", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :name_hurigana, "ふりがな", style: "display: block" %>
    <%= form.text_field :name_hurigana %>
  </div>

  <div>
    <%= form.label :grade, "学年", style: "display: block" %>
    <%= form.select :grade, grades_options %>
  </div>

  <div>
    <%= form.label :goal, "目標にしていること", style: "display: block" %>
    <%= form.text_field :goal %>
  </div>

  <div>
    <%= form.label :level, "学力", style: "display: block" %>
    <% levels_options.each do |label, value| %>
      <%= form.radio_button :level, value, id: "student_level_#{value}" %>
      <%= form.label "level_#{value}", label %>　
    <% end %>
  </div>

  <div>
    <%= form.label :attitude, "授業態度", style: "display: block" %>
    <% attitudes_options.each do |label, value| %>
      <%= form.radio_button :attitude, value, id: "student_attitude_#{value}", class: "attitude" %>
      <%= form.label "attitude_#{value}", label %>　
    <% end %>
  </div>

  <div id="how-to-focus" style="display: none">
    <%= form.label :how_to_focus, "やる気がないときは？", style: "display: block" %>
    <%= form.text_field :how_to_focus %>
  </div>

  <div>
    <%= form.label :personality, "その他の性格", style: "display: block" %>
    <%= form.text_field :personality %>
  </div>

  <diV>
    <%= form.label :school_id, "校舎", style: "display: block" %>
    <div style="display: flex;">
      <div>
        <% Arium.all.each do |category| %>
          <%= form.radio_button :area, category.id, class: "area" %>
          <%= form.label "area_#{category.id}", category.name %><br>
        <% end %>
        <input type="hidden" id="area-id" value=<%= current_teacher.area %>>
      </div>

      <div>
        <% Prefecture.all.each do |category| %>
          <%= form.radio_button :prefecture, category.id, class: "#{category.area_id} prefecture" %>
          <%= form.label "prefecture_id_#{category.id}", category.name, class: "#{category.area_id} prefecture" %><br class="<%= category.area_id %> prefecture">
        <% end %>
        <input type="hidden" id="prefecture-id" value=<%= current_teacher.prefecture %>>
      </div>

      <div>
        <% School.all.order(:school_id).each do |category| %>
          <%= form.radio_button :school_id, category.id, class: "pref-#{category.prefecture_id} school" %>
          <%= form.label "school_id_#{category.id}", "#{category.name}(#{category.school_id})", class: "pref-#{category.prefecture_id} school" %><br class="pref-<%= category.prefecture_id %> school">
        <% end %>
      </div>
    </div>
  </div>

  <div>
    <h2>生徒の補足</h2>
    <%= form.text_area :supplement %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


<script>
  $.fn.autoKana('#student_name', '#student_name_hurigana');

  var idArray = ["#student_name", "#student_goal", "#student_personality", "#student_supplement"];

  for (let i = 0; i<idArray.length-1; i++){
    const currentId = idArray[i];
    const nextId = idArray[i+1];
    $(currentId).keypress(function(event) {
      if (event.keyCode === 13) {
        event.preventDefault();
        $(nextId).focus();
      }
    });
  }
  
  var currentArea = 0;
  var currentPrefecture = 0;

  $(".area").on("click", function(){
    const selectedValue = $('input[name="student[area]"]:checked').val();
    if(currentArea != selectedValue){
      currentArea = selectedValue;
      currentPrefecture = 0;
      $(".prefecture").css("display", "none").prop('checked', false);
      $("." + selectedValue).css("display", "inline-block");
      $(".school").css("display", "none").prop('checked', false);
    }
  });

  $(".prefecture").css("display", "none").on("click", function(){
    const selectedValue = $('input[name="student[prefecture]"]:checked').val();
    if(currentPrefecture != selectedValue){
      currentPrefecture = selectedValue;
      $(".school").css("display", "none").prop('checked', false);
      $(".pref-" + selectedValue).css("display", "inline-block");
    }
  });
  $("." + $("#area-id").val() ).css("display", "inline-block");

  $(".school").css("display", "none");
  $(".pref-" + $("#prefecture-id").val() ).css("display", "inline-block");

  $(".attitude").on("click", function(){
    const selectedValue = $('input[name="student[attitude]"]:checked').val();
    if(selectedValue){
      if(selectedValue == 3){
        $("#how-to-focus").css("display", "none");
      } else{
        $("#how-to-focus").css("display", "block");
      }
    }
  });

</script>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>" class="school-<%= student.school_id %> student">

  <% if action_name == "index" %>
    <div style="display: flex;">
      <p style="padding-right: 2em; margin-block-end: 0px">
        <strong>名前:</strong>
        <%= student.name %>(<%= student.name_hurigana %>)
      </p>

      <p style=" margin-block-end: 0px">
        <strong>学年:</strong>
        <%= ["小学1年", "小学2年", "小学3年", "小学4年", "小学5年", "小学6年", "中学1年", "中学2年", "中学3年", "高校1年", "高校2年", "高校3年", "既卒"][student.grade - 1] %>
      </p>
    </div>
  <% else %>
    <div style="display: flex;">
      <div style="padding-right: 2em; max-width: 50vw">
        <p>
          <strong>名前:</strong>
          <%= student.name %>(<%= student.name_hurigana %>)
        </p>

        <p>
          <strong>学年:</strong>
          <%= ["小学1年", "小学2年", "小学3年", "小学4年", "小学5年", "小学6年", "中学1年", "中学2年", "中学3年", "高校1年", "高校2年", "高校3年", "既卒"][student.grade - 1] %>
        </p>

        <p>
          <strong>目標にしていること:</strong>
          <%= student.goal %>
        </p>

        <p>
          <strong>学力:</strong>
          <%= ["かなり前の内容から復習が必要","復習が必要","学校の授業に合わせたらいい","少し予習も取り入れている"][student.level - 1] %>
        </p>

        <p>
          <strong>授業態度:</strong>
          <%= ["全然集中しない","やる気にムラがある","いつも集中している"][student.attitude - 1] %>
        </p>

        <% unless student.attitude == 3 %>
          <p>
            <strong>やる気がないときは:</strong>
            <%= student.how_to_focus %>
          </p>
        <% end %>

        <p>
          <strong>性格:</strong>
          <%= student.personality %>
        </p>
      </div>

      <div>
        <strong>補足情報</strong>
        <% unless student.supplement.blank? %>
          <div style="padding: 0 2em;">
            <%= simple_format(student.supplement) %>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>生徒一覧</h1>

<%= link_to "生徒を追加", new_student_path %>

<input type="hidden" id="teacher-school-id" value=<%= current_teacher.school_id %>>

<%= form_with do |form| %>
  <div>
    <%= form.label :school_id, "校舎", style: "display: block" %>
    <div style="display: flex;">
      <div>
        <% Arium.all.each do |category| %>
          <%= form.radio_button :area, category.id, class: "area", checked: (category.id == current_teacher.area) %>
          <%= form.label "area_#{category.id}", category.name %><br>
        <% end %>
        <input type="hidden" id="area-id" value=<%= current_teacher.area %>>
      </div>

      <div>
        <% Prefecture.all.each do |category| %>
          <%= form.radio_button :prefecture, category.id, class: "#{category.area_id} prefecture", checked: (category.id == current_teacher.prefecture) %>
          <%= form.label "prefecture_id_#{category.id}", category.name, class: "#{category.area_id} prefecture" %><br class="<%= category.area_id %> prefecture">
        <% end %>
        <input type="hidden" id="prefecture-id" value=<%= current_teacher.prefecture %>>
      </div>

      <div>
        <% School.all.order(:school_id).each do |category| %>
          <%= form.radio_button :school, category.id, class: "pref-#{category.prefecture_id} school", checked: (category.id == current_teacher.school_id) %>
          <%= form.label "school_id_#{category.id}", "#{category.name}(#{category.school_id})", class: "pref-#{category.prefecture_id} school" %><br class="pref-<%= category.prefecture_id %> school">
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p class="school-<%= student.school_id %> student" style="margin-block-start: 0px">
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "生徒を追加", new_student_path %>

<script>

  var currentArea = 0;
  var currentPrefecture = 0;
  var currentSchool = 0;

  $(".student").css("display","none");
  $(".school-" + $("#teacher-school-id").val()).css("display","block");

  $(".area").on("click", function(){
    const selectedValue = $('input[name="area"]:checked').val();
    if(currentArea != selectedValue){
      currentArea = selectedValue;
      currentPrefecture = 0
      currentSchool = 0;
      $(".prefecture").css("display", "none").prop('checked', false);
      $("." + selectedValue).css("display", "inline-block");
      $(".school").css("display", "none").prop('checked', false);
      $(".student").css("display", "none");
    }
  });

  $(".prefecture").css("display", "none").on("click", function(){
    const selectedValue = $('input[name="prefecture"]:checked').val();
    if(currentPrefecture != selectedValue){
      currentPrefecture = selectedValue;
      $(".school").css("display", "none").prop('checked', false);
      $(".pref-" + selectedValue).css("display", "inline-block");
      $(".student").css("display", "none");
    }
  });
  $("." + $("#area-id").val() ).css("display", "inline-block");

  $(".school").css("display", "none").on("click", function(){
    const selectedValue = $('input[name="school"]:checked').val();
    if(currentSchool != selectedValue){
      currentSchool = selectedValue;
      $(".student").css("display", "none");
      $(".school-" + selectedValue).css("display", "block");
    }
  });
  $(".pref-" + $("#prefecture-id").val() ).css("display", "inline-block");

</script>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete, form: {data: {turbo_confirm: "本当に削除してもよろしいですか？"}} %>
</div>


<p>
  <%= link_to "授業データを追加", new_main_path %>
</p>
<h3>授業データ一覧</h3>
<ul>
  <% @student.mains.each do |main| %>
    <%= link_to main do %>
      <li><%= main.updated_at %>(<%= ["国語", "算数・数学", "理科", "社会", "英語"][main.subject - 1] %>)</li>
    <% end %>
  <% end %>
</ul>