config/routes.rb
Rails.application.routes.draw do
  resources :chats, except: [:edit, :update]
  resources :testbooks
  resources :mains
  resources :prefectures
  resources :aria
  resources :schools
  resources :students
  devise_for :teachers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'teachers', to: 'teachers#index'
  get 'teachers/:id', to: 'teachers#show'
  patch "teacher/:id", to: "teachers#authentication", as: "teacher"
  post "search_teacher", to: "tops#search_teacher"
  post "ask_approve", to: "tops#ask_approve"
  get "update_grade", to: "tops#update_grade"
  get "chats/new/:teacher_id", to: "chats#new"

  # Defines the root path route ("/")
  # root "articles#index"
  root 'tops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/arium.rb
class Arium < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :teacher

end

app/models/flow.rb
class Flow < ApplicationRecord

  belongs_to :main

end

app/models/homework.rb
class Homework < ApplicationRecord

  validates :main_id, uniqueness: { scope: :textbook_id }

  belongs_to :main
  belongs_to :textbook, class_name: "Testbook"

end

app/models/main.rb
class Main < ApplicationRecord

  belongs_to :student

  has_many :flows, dependent: :destroy
  accepts_nested_attributes_for :flows, reject_if: proc {|attributes| attributes['content'].blank?}, allow_destroy: true
  
  has_many :main_textbooks, dependent: :destroy
  accepts_nested_attributes_for :main_textbooks, reject_if: proc {|attributes| attributes['textbook_id'].blank?}, allow_destroy: true

  has_many :homeworks, dependent: :destroy
  accepts_nested_attributes_for :homeworks, reject_if: proc {|attributes| attributes['textbook_id'].blank?}, allow_destroy: true

  def textbooks_hash
    ret = {}
    self.main_textbooks.each do |mt|
      t = Testbook.find_by(id: mt.textbook_id)
      ret[t.id] = {id: mt.id, name: t.name, finished_place: mt.finished_place} if t
    end
    return ret
  end
  
  def homeworks_hash
    ret = {}
    self.homeworks.each do |h|
      t = Testbook.find_by(id: h.textbook_id)
      ret[t.id] = {id: h.id, name: t.name, amount: h.amount} if t
    end
    return ret
  end

  def student
    unless self.student_id.blank?
      return Student.find(self.student_id)
    else
      return Student.find(session[:student_id]) if session[:student_id]
    end
    return nil
  end

  def textbook_ids
    arr = []
    self.main_textbooks.each do |mt|
      arr.push(mt.textbook_id)
    end
    return arr
  end

  def homework_ids
    arr = []
    self.homeworks.each do |h|
      arr.push(h.textbook_id)
    end
    return arr
  end

end

app/models/main_textbook.rb
class MainTextbook < ApplicationRecord

  validates :main_id, uniqueness: { scope: :textbook_id }

  belongs_to :main
  belongs_to :textbook, class_name: "Testbook"

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  def hash_format
    return {id: self.id, name: self.name}
  end
  
end

app/models/school.rb
class School < ApplicationRecord
  
  validates :name, presence: :true
  validates :school_id, presence: :true
  validates :prefecture_id, presence: :true
  validates :name, uniqueness: true
  validates :school_id, uniqueness: :true

  def hash_format
    return {id: self.id, name: self.name}
  end
  
end

app/models/student.rb
class Student < ApplicationRecord

  validates :level, presence: :true
  validates :attitude, presence: :true
  has_many :mains, -> { order(updated_at: :desc) }

  def area
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    a = Arium.find_by(id: p.area_id) if p
    return a.id if a
  end

  def prefecture
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    return p.id if p
  end

  def school
    return School.find_by(id: self.school_id)
  end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :chats

  def area
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    a = Arium.find_by(id: p.area_id) if p
    return a.id if a
  end

  def prefecture
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    return p.id if p
  end

  def school
    return School.find_by(id: self.school_id)
  end

  def hash_format
    if self.school.blank?
      return {id: self.id, name: self.name, school: ""}
    else
      return {id: self.id, name: self.name, school: self.school.name}
    end
  end

end

app/models/testbook.rb
class Testbook < ApplicationRecord
  validates :name, uniqueness: true
  validates :name_kana, presence: :true
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
  end

  def ask_approve
    new_teacher = Teacher.find_by(id: params[:new_teacher_id])
    old_teacher = Teacher.find_by(id: params[:old_teacher_id])
    if old_teacher.nil?
      render json: "error"
    else
      UserMailer.ask_approve(old_teacher, new_teacher).deliver_now
      render json: "success"
    end
  end

  def search_teacher
    ret = []
    Teacher.where("name LIKE ? OR name_kana LIKE ?", "#{params[:name]}%", "#{params[:name_kana]}%").where(is_authenticated: true).order(:id).each do |teacher|
      ret.push(teacher.hash_format)
    end
    render json: ret
  end

  def update_grade
    remote_ip = request.remote_ip
    logger.info remote_ip
    if remote_ip == ENV["MY_IP"]
      Student.all.each do |student|
        student.grade = student.grade + 1 unless student.grade == 13
        student.save
      end
    end
    render json: {ip: remote_ip}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aria_helper.rb
module AriaHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/mains_helper.rb
module MainsHelper

  def subjects_options
    return {"国語" => 1, "算数・数学" => 2, "理科" => 3, "社会" => 4, "英語" => 5}
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def grades_options
    options = {}
    (1..6).each do |n|
      options = options.merge({"小学#{n}年" => n})
    end
    (7..9).each do |n|
      options = options.merge({"中学#{n-6}年" => n})
    end
    (10..12).each do |n|
      options = options.merge({"高校#{n-9}年" => n})
    end
    options = options.merge({"既卒" => 13})
    return options
  end

  def levels_options
    return {"かなり前の内容から復習が必要" => 1, "復習が必要" => 2, "学校の授業に合わせたらいい" => 3, "少し予習も取り入れている" => 4}
  end
  
  def attitudes_options
    return {"全然集中しない" => 1, "やる気にムラがある" => 2, "いつも集中している" => 3}
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/testbooks_helper.rb
module TestbooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<h1>TRY 引継ぎシステム</h1>

<% if teacher_signed_in? %>
  <% if !(current_teacher.is_authenticated) %>
    <div>
      承認されていないユーザです。<br>
      <div id="teachers">
        <% Teacher.where(school_id: current_teacher.school_id).where(is_authenticated: true).each do |teacher| %>
          <input type="radio" name="teacher" id="teacher-<%= teacher.id %>" value=<%= teacher.id %>>
          <label for="teacher-<%= teacher.id %>"><%= teacher.name %>先生</label><br>
        <% end %>
        <input type="hidden" id="new_teacher_id" value="<%= current_teacher.id %>">
      </div>
      知っている先生がいない場合はこちら<input type="text" id="name" placeholder="教師名">(<input type="text" id="name_kana" placeholder="かな">)先生<button onclick="searchTeacher()">検索</button>
      <button id="approve-btn" onclick="askApprove()">に承認してもらう。</button>
    </div>
  <% else %>
    <ul>
      <li><%= link_to '生徒一覧', students_path %></li>
      <li><%= link_to '校舎一覧', schools_path %></li>
      <% if current_teacher.email == ENV['ADMIN_EMAIL'] %>
        <li><%= link_to '地方の編集', aria_path %></li>
      <% end %>
    </ul>
  <% end %>
<% else %>
  <ul>
    <li><%= link_to 'Sign In', new_teacher_session_path %></li>
    <li><%= link_to 'Sign Up', new_teacher_registration_path %></li>
  </ul>
<% end %>

<script>

  $.fn.autoKana('#name', '#name_kana');

  function searchTeacher(){
    const name = $('#name').val();
    const name_kana = $('#name_kana').val();
    if(name == "" || name_kana == ""){
      alert("教師名を入力してください。");
    } else{
      setCSRFtoken();
      $.post("/search_teacher", {name: name, name_kana: name_kana}, function(data){
        console.log(data);
        $("#teachers").html("");
        for(let teacher of data){
          $("#teachers").append("<input type='radio' name='teacher' id='teacher-" + teacher.id + "' value='" + teacher.id + "'><label for='teacher-" + teacher.id + "'>" + teacher.name + "先生(" + teacher.school + ")</label><br>");
        }
      });
    }
  }

  function askApprove(){
    const old_teacher_id = $('input[name="teacher"]:checked').val();
    const new_teacher_id = $('#new_teacher_id').val();
    if(old_teacher_id){
      setCSRFtoken();
      $("#approve-btn").css("display", "none");
      $.post("/ask_approve", {old_teacher_id: old_teacher_id, new_teacher_id: new_teacher_id}, function(data){
        $("#approve-btn").css("display", "inline-block");
        if(data == "error"){
          alert("承認メールを送信できませんでした。");
        }
      }, "text");
    }else{
      alert("承認してもらう教師を選択してください。");
    }
  }

</script>