config/routes.rb
Rails.application.routes.draw do
  resources :chats, except: [:edit, :update]
  resources :testbooks
  resources :mains
  resources :prefectures
  resources :aria
  resources :schools
  resources :students
  devise_for :teachers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'teachers', to: 'teachers#index'
  get 'teachers/:id', to: 'teachers#show'
  patch "teacher/:id", to: "teachers#authentication", as: "teacher"
  post "search_teacher", to: "tops#search_teacher"
  post "ask_approve", to: "tops#ask_approve"
  get "update_grade", to: "tops#update_grade"
  get "chats/new/:teacher_id", to: "chats#new"

  # Defines the root path route ("/")
  # root "articles#index"
  root 'tops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/arium.rb
class Arium < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :teacher

end

app/models/flow.rb
class Flow < ApplicationRecord

  belongs_to :main

end

app/models/homework.rb
class Homework < ApplicationRecord

  validates :main_id, uniqueness: { scope: :textbook_id }

  belongs_to :main
  belongs_to :textbook, class_name: "Testbook"

end

app/models/main.rb
class Main < ApplicationRecord

  belongs_to :student

  has_many :flows, dependent: :destroy
  accepts_nested_attributes_for :flows, reject_if: proc {|attributes| attributes['content'].blank?}, allow_destroy: true
  
  has_many :main_textbooks, dependent: :destroy
  accepts_nested_attributes_for :main_textbooks, reject_if: proc {|attributes| attributes['textbook_id'].blank?}, allow_destroy: true

  has_many :homeworks, dependent: :destroy
  accepts_nested_attributes_for :homeworks, reject_if: proc {|attributes| attributes['textbook_id'].blank?}, allow_destroy: true

  def textbooks_hash
    ret = {}
    self.main_textbooks.each do |mt|
      t = Testbook.find_by(id: mt.textbook_id)
      ret[t.id] = {id: mt.id, name: t.name, finished_place: mt.finished_place} if t
    end
    return ret
  end
  
  def homeworks_hash
    ret = {}
    self.homeworks.each do |h|
      t = Testbook.find_by(id: h.textbook_id)
      ret[t.id] = {id: h.id, name: t.name, amount: h.amount} if t
    end
    return ret
  end

  def student
    unless self.student_id.blank?
      return Student.find(self.student_id)
    else
      return Student.find(session[:student_id]) if session[:student_id]
    end
    return nil
  end

  def textbook_ids
    arr = []
    self.main_textbooks.each do |mt|
      arr.push(mt.textbook_id)
    end
    return arr
  end

  def homework_ids
    arr = []
    self.homeworks.each do |h|
      arr.push(h.textbook_id)
    end
    return arr
  end

end

app/models/main_textbook.rb
class MainTextbook < ApplicationRecord

  validates :main_id, uniqueness: { scope: :textbook_id }

  belongs_to :main
  belongs_to :textbook, class_name: "Testbook"

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  def hash_format
    return {id: self.id, name: self.name}
  end
  
end

app/models/school.rb
class School < ApplicationRecord
  
  validates :name, presence: :true
  validates :school_id, presence: :true
  validates :prefecture_id, presence: :true
  validates :name, uniqueness: true
  validates :school_id, uniqueness: :true

  def hash_format
    return {id: self.id, name: self.name}
  end
  
end

app/models/student.rb
class Student < ApplicationRecord

  validates :level, presence: :true
  validates :attitude, presence: :true
  has_many :mains, -> { order(updated_at: :desc) }

  def area
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    a = Arium.find_by(id: p.area_id) if p
    return a.id if a
  end

  def prefecture
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    return p.id if p
  end

  def school
    return School.find_by(id: self.school_id)
  end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :chats

  def area
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    a = Arium.find_by(id: p.area_id) if p
    return a.id if a
  end

  def prefecture
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    return p.id if p
  end

  def school
    return School.find_by(id: self.school_id)
  end

  def hash_format
    if self.school.blank?
      return {id: self.id, name: self.name, school: ""}
    else
      return {id: self.id, name: self.name, school: self.school.name}
    end
  end

end

app/models/testbook.rb
class Testbook < ApplicationRecord
  validates :name, uniqueness: true
  validates :name_kana, presence: :true
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: %i[ show edit update destroy ]

  # GET /mains or /mains.json
  def index
    @mains = Main.all
  end

  # GET /mains/1 or /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    if session[:student_id].blank?
      redirect_to students_path
    end
    @main = Main.new
    @main.student_id = session[:student_id].to_i
    @main.flows.new
  end

  # GET /mains/1/edit
  def edit
    @main.flows.new
  end

  # POST /mains or /mains.json
  def create
    @main = Main.new(main_params)
    respond_to do |format|
      if @main.save
        @main.flows.each do |flow|
          flow.order = flow.id
          flow.save
        end
        format.html { redirect_to main_url(@main), notice: "Main was successfully created." }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mains/1 or /mains/1.json
  def update
    student_id = @main.student_id
    respond_to do |format|
      if @main.update(main_params)
        @main.flows.each do |flow|
          if flow.order.nil?
            flow.order = flow.id
            flow.save
          end
        end
        @main.student_id = student_id
        @main.updated_at = Time.now
        @main.save
        format.html { redirect_to main_url(@main), notice: "Main was successfully updated." }
        format.json { render :show, status: :ok, location: @main }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1 or /mains/1.json
  def destroy
    student_id = @main.student_id
    @main.destroy

    respond_to do |format|
      format.html { redirect_to "#{students_path}/#{student_id}", notice: "授業データを削除しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main
      @main = Main.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def main_params
      params.require(:main).permit(:subject, :student_id, :is_giving_answer, :supplement, flows_attributes: [:id, :content], main_textbooks_attributes: [:id, :finished_place, :textbook_id], homeworks_attributes: [:id, :amount, :textbook_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aria_helper.rb
module AriaHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/mains_helper.rb
module MainsHelper

  def subjects_options
    return {"国語" => 1, "算数・数学" => 2, "理科" => 3, "社会" => 4, "英語" => 5}
  end

end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def grades_options
    options = {}
    (1..6).each do |n|
      options = options.merge({"小学#{n}年" => n})
    end
    (7..9).each do |n|
      options = options.merge({"中学#{n-6}年" => n})
    end
    (10..12).each do |n|
      options = options.merge({"高校#{n-9}年" => n})
    end
    options = options.merge({"既卒" => 13})
    return options
  end

  def levels_options
    return {"かなり前の内容から復習が必要" => 1, "復習が必要" => 2, "学校の授業に合わせたらいい" => 3, "少し予習も取り入れている" => 4}
  end
  
  def attitudes_options
    return {"全然集中しない" => 1, "やる気にムラがある" => 2, "いつも集中している" => 3}
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/testbooks_helper.rb
module TestbooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/mains/_form.html.erb
<%= form_with(model: main) do |form| %>
  <% if main.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
        <% main.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :student_id %>

  <div>
    <%= form.label :subject, "教科", style: "display: block" %>
    <%= form.select :subject, subjects_options  %>
  </div>

  <div style="display: flex;">
    <div style="padding-right: 2em;" id="textbooks">
      <h2>使用している教材</h2>
      <% Testbook.all.order(:name_kana).each do |textbook| %>
        <div class="<%= textbook.name_kana %> textbook">
          <% if main.textbook_ids.include?(textbook.id) || main.homework_ids.include?(textbook.id) %>
            <input type="checkbox" name="textbook[]" id="textbook_<%= textbook.id %>" value="<%= textbook.id %>" onclick="setTextbookAndHomeworkForm()" checked>
          <% else %>
            <input type="checkbox" name="textbook[]" id="textbook_<%= textbook.id %>" value="<%= textbook.id %>" onclick="setTextbookAndHomeworkForm()">
          <% end %>
          <label for="textbook_<%= textbook.id %>" id="textbook-name-<%= textbook.id %>"><%= textbook.name %></label>
        </div>
      <% end %>
    </div>
    <div>
      教材が見つからない場合はこちら<br>
      <input type="text" id="text-name" placeholder="教材名" oninput="searchTextbook()"><br>
      <input type="text" id="text-name-kana" placeholder="ふりがな" oninput="searchTextbook()"><br>
      <button type="button" onclick="addTextbook()">教材を追加</button>
    </div>
  </div>

  <h2>どこまでやったか</h2>
  <div id="finished_place">
  </div>

  <div id="flows">
    <h2>授業の流れ</h2>
    <% i = 0 %>
    <%= form.fields_for :flows do |flow_form| %>
      <% if i != 0 %>
        <br>↓<br>
      <% end %>
      <%= flow_form.text_field :content, placeholder: "例題を解説" %>
      <% i = i + 1 %>
    <% end %>
    <input type="hidden" id="flows-length" value="<%= i %>">
  </div>
  <button type="button" onclick="addFlow()">授業の流れを追加</button>

  <div>
    <h2>宿題の量</h2>
    <div id="homeworks">
    </div>
    <p>
      <% if main.is_giving_answer.nil? %>
        <input type="radio" name="main[is_giving_answer]" id="main_is_giving_answer_f" value="0"><label for="main_is_giving_answer_f">宿題の答えは丸付けをしたあと渡す</label>
        <input type="radio" name="main[is_giving_answer]" id="main_is_giving_answer_t" value="1"><label for="main_is_giving_answer_t">宿題を自分で丸付けしてもらう</label>
      <% elsif main.is_giving_answer %>
        <input type="radio" name="main[is_giving_answer]" id="main_is_giving_answer_f" value="0"><label for="main_is_giving_answer_f">宿題の答えは丸付けをしたあと渡す</label>
        <input type="radio" name="main[is_giving_answer]" id="main_is_giving_answer_t" value="1" checked><label for="main_is_giving_answer_t">宿題を自分で丸付けしてもらう</label>
      <% else %>
        <input type="radio" name="main[is_giving_answer]" id="main_is_giving_answer_f" value="0" checked><label for="main_is_giving_answer_f">宿題の答えは丸付けをしたあと渡す</label>
        <input type="radio" name="main[is_giving_answer]" id="main_is_giving_answer_t" value="1"><label for="main_is_giving_answer_t">宿題を自分で丸付けしてもらう</label>
      <% end %>
    </p>
  </div>

  <div>
    <h2>授業の補足</h2>
    <%= form.text_area :supplement %>
  </div>

  <div>
    <%= form.submit "授業データの作成・更新" %>
  </div>
<% end %>

<script>

  var flowsLength = Number( $("#flows-length").val() );
  var textbookData = <%= raw main.textbooks_hash.to_json %>
  var homeworkData = <%= raw main.homeworks_hash.to_json %>

  //関数の定義
  function addFlow(){
    $("#flows").append('<br>↓<br><input type="text" name="main[flows_attributes][' + flowsLength + '][content]" id="main_flows_attributes_' + flowsLength + '_content">');
    $('#main_flows_attributes_' + flowsLength + '_content').focus().keypress(function(event){
      if (event.keyCode === 13) {
        event.preventDefault();
      }
    });;
    flowsLength++;
  }

  function addTextbook(){
    setCSRFtoken();
    $.post("/testbooks.json", {testbook: {name: $("#text-name").val(), name_kana: $("#text-name-kana").val()}}, function(data){
      $("#textbooks").append(`<div class="${data.name_kana} textbook"><input type="checkbox" name="textbook[]" id="textbook_${data.id}" value="${data.id}" onclick="setTextbookAndHomeworkForm()" checked><label for="textbook_${data.id}" id="textbook-name-${data.id}">${data.name}</label></div>`);
      setTextbookAndHomeworkForm();
      $("#text-name").val("");
      $("#text-name-kana").val("");
      searchTextbook();
    });
  }

  function setTextBookData(key, i){
    const value = $(`#main_main_textbooks_attributes_${i}_finished_place`).val()
    if(textbookData[key]){
      textbookData[key]["finished_place"] = value;
    } else{
      textbookData[key] = {id: "", finished_place: value};
    }
  }

  function setHomeworkData(key, i){
    const value = $(`#main_homeworks_attributes_${i}_finished_place`).val()
    if(homeworkData[key]){
      homeworkData[key]["amount"] = value;
    } else{
      homeworkData[key] = {id: "", amount: value};
    }
  }

  function setTextbookAndHomeworkForm(){
    var selectedValues = $('input[name="textbook[]"]:checked').map(function(){
      return $(this).val();
    }).get();
    const fKeys = Object.keys(textbookData);
    const hKeys = Object.keys(homeworkData);
    if(selectedValues.length == 0){
      $("#finished_place").html("使用している教材を選択してください。");
      $("#homeworks").html("使用している教材を選択してください。");
    } else{
      $("#finished_place").html("");
      $("#homeworks").html("");
      for(let i=0; i<selectedValues.length; i++){
        const value = selectedValues[i];
        const name = $(`#textbook-name-${value}`).text();
        if(fKeys.includes(value)){
          const tElem = textbookData[value];
          $("#finished_place").append(`<label for="main_main_textbooks_attributes_${i}_finished_place">${name}</label>：<input type="text" name="main[main_textbooks_attributes][${i}][finished_place]" id="main_main_textbooks_attributes_${i}_finished_place" oninput="setTextBookData(${value}, ${i})" value="${tElem.finished_place}"><input type="hidden" value="${value}" name="main[main_textbooks_attributes][${i}][textbook_id]" id="main_main_textbooks_attributes_${i}_textbook_id"><input type="hidden" value="${tElem.id}" name="main[main_textbooks_attributes][${i}][id]" id="main_main_textbooks_attributes_${i}_id"><br>`);
        } else{
          $("#finished_place").append(`<label for="main_main_textbooks_attributes_${i}_finished_place">${name}</label>：<input type="text" name="main[main_textbooks_attributes][${i}][finished_place]" id="main_main_textbooks_attributes_${i}_finished_place" oninput="setTextBookData(${value}, ${i})"><input type="hidden" value="${value}" name="main[main_textbooks_attributes][${i}][textbook_id]" id="main_main_textbooks_attributes_${i}_textbook_id"><br>`);
        }
        if(hKeys.includes(value)){
          const hElem = homeworkData[value];
          $("#homeworks").append(`<label for="main_homeworks_attributes_${i}_amount">${name}</label>：<input type="text" name="main[homeworks_attributes][${i}][amount]" id="main_homeworks_attributes_${i}_amount" oninput="setHomeworkData(${value}, ${i})" value="${hElem.amount}">/週<input type="hidden" value="${value}" name="main[homeworks_attributes][${i}][textbook_id]" id="main_homeworks_attributes_${i}_textbook_id"><input type="hidden" value="${hElem.id}" name="main[homeworks_attributes][${i}][id]" id="main_homeworks_attributes_${i}_id"><br>`);
        } else{
          $("#homeworks").append(`<label for="main_homeworks_attributes_${i}_amount">${name}</label>：<input type="text" name="main[homeworks_attributes][${i}][amount]" id="main_homeworks_attributes_${i}_amount" oninput="setHomeworkData(${value}, ${i})">/週<input type="hidden" value="${value}" name="main[homeworks_attributes][${i}][textbook_id]" id="main_homeworks_attributes_${i}_textbook_id"><br>`);
        }
        $(`#main_main_textbooks_attributes_${i}_finished_place`).keypress(function(event){
          if (event.keyCode === 13) {
            event.preventDefault();
          }
        });
        $(`main_homeworks_attributes_${i}_amount`).keypress(function(event){
          if (event.keyCode === 13) {
            event.preventDefault();
          }
        });
      }
    }
  }

  function searchTextbook(){
    const name = $("#text-name").val();
    const name_kana = $("#text-name-kana").val();
    if(name == "" && name_kana == "") {
      $(".textbook").each(function() {
        $(this).css("display","block");
      });
    } else{
      $(".textbook").each(function() {
        if(name_kana == ""){
          if( $(this).text().includes(name) ){
            $(this).css("display","block");
          } else {
            $(this).css("display","none");
          }
        } else if( $(this).text().includes(name) || $(this).attr("class").split(" ")[0].includes(name_kana) ){
          $(this).css("display","block");
        } else{
          $(this).css("display","none");
        }
      });
    }
  }

  //関数の実行s
  $.fn.autoKana('#text-name', '#text-name-kana');

  setTextbookAndHomeworkForm();

  $("input[type=text]").each(function(){
    if($(this).attr("id")){
      if( ['#text-name', '#text-name-kana'].includes($(this).attr("id")) ){} else{
        $(this).keypress(function(event){
          if (event.keyCode === 13) {
            event.preventDefault();
          }
        });
      }
    }
  });
  
  $('#text-name').keypress(function(event) {
    if (event.keyCode === 13) {
      event.preventDefault();
      $("#text-name-kana").focus();
    }
  });

  $('#text-name-kana').keypress(function(event) {
    if (event.keyCode === 13) {
      event.preventDefault();
      addTextbook();
    }
  });

  var idArray = ["#student_name", "#student_goal", "#student_personality", "#student_supplement"];

  for (let i = 0; i<idArray.length-1; i++){
    const currentId = idArray[i];
    const nextId = idArray[i+1];
    $(currentId).keypress(function(event) {
      if (event.keyCode === 13) {
        event.preventDefault();
        $(nextId).focus();
      }
    });
  }

</script>

app/views/mains/_main.html.erb
<div id="<%= dom_id main %>">
  <p>
    <strong>Subject:</strong>
    <%= ["国語", "算数・数学", "理科", "社会", "英語"][main.subject - 1] %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= main.student.name %>
  </p>

</div>

app/views/mains/edit.html.erb
<h1><%= @main.student.name %>さん　<%= ["国語", "算数・数学", "理科", "社会", "英語"][@main.subject - 1] %>　授業データの編集</h1>

<%= render "form", main: @main %>

<br>

<div>
  <%= link_to "Show this main", @main %> |
  <%= link_to "生徒詳細ページへ戻る", @main.student %>
</div>

app/views/mains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mains</h1>

<div id="mains">
  <% @mains.each do |main| %>
    <%= render main %>
    <p>
      <%= link_to "Show this main", main %>
    </p>
  <% end %>
</div>

<%= link_to "New main", new_main_path %>

app/views/mains/new.html.erb
<h1>New main</h1>

<%= render "form", main: @main %>

<br>

<div>
  <%= link_to "生徒詳細ページへ戻る", @main.student %>
</div>

app/views/mains/show.html.erb
<p class="no-print" style="color: green"><%= notice %></p>

<h1><%= @main.student.name %>さん（<%= ["国語", "算数・数学", "理科", "社会", "英語"][@main.subject - 1] %>）<span class="no-print">授業データ</span><span class="only-print-inline">を担当される先生へ</span></h1>
  
<hr>

<div class="no-print">
  <%= link_to "授業データの編集", edit_main_path(@main) %> |
  <%= link_to "生徒データの編集", edit_student_path(@main.student) %> |
  <%= link_to "生徒詳細ページへ戻る", @main.student %>

  <%= button_to "授業データの削除", @main, method: :delete, form: {data: {turbo_confirm: "本当に削除してもよろしいですか？"}} %>

  内容を確認して最下部の「印刷」ボタンをクリックすると印刷できます。
</div>
<div>
  <h2 style="margin-block-start: 0em; margin-block-end: 0em;">生徒情報</h2>
  <div style="padding: 0 2em;">
    <%= render "students/student", student: @main.student %>
  </div>
  
  <hr>
  
  <h2 style="margin-block-start: 0em; margin-block-end: 0em;">授業情報</h2>
  <div style="display: flex;">
    <div style="padding-right: 2em; max-width: 50vw;">
      <h3>どこまでやったか</h3>
      <ul>
        <% @main.textbooks_hash.each do |key, value| %>
          <% unless value[:finished_place].blank? %>
            <li><b><%= value[:name] %>：</b><%= value[:finished_place] %></li>
          <% end %>
        <% end %>
      </ul>

      <h3>授業の流れ</h3>
      <ol>
        <% @main.flows.each do |flow| %>
          <% unless flow.content.blank? %>
            <li><%= flow.content %></li>
          <% end %>
        <% end %>
      </ol>

      <h3>宿題について</h3>
      
      <% if @main.is_giving_answer %>
        <strong>※　宿題を自分で丸付けしてもらっています。</strong>
      <% else %>
        <strong>※　宿題の答えは丸付けをしたあと渡しています。</strong>
      <% end %>
      
      <br><br><strong style="padding: 0 1em;">量</strong>
      <ul>
        <% @main.homeworks_hash.each do |key, value| %>
          <% unless value[:amount].blank? %>
            <li><b><%= value[:name] %>：</b><%= value[:amount] %>/週</li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div>
      <h3>授業の補足</h3>
      <% unless @main.supplement.blank? %>
        <div style="padding: 0 2em;">
          <%= simple_format(@main.supplement) %>
        </div>
      <% end %>
    </div>
  </div>
  <p style="width: 95vw; text-align: right;">以上です。引継ぎお願いします。　<b><%= current_teacher.name %><b></p>
  <p class="no-print"><button onclick="window.print();">印刷</button></p>
</div>