config/routes.rb
Rails.application.routes.draw do
  resources :chats, except: [:edit, :update]
  resources :testbooks
  resources :mains
  resources :prefectures
  resources :aria
  resources :schools
  resources :students
  devise_for :teachers

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'teachers', to: 'teachers#index'
  get 'teachers/:id', to: 'teachers#show'
  patch "teacher/:id", to: "teachers#authentication", as: "teacher"
  post "search_teacher", to: "tops#search_teacher"
  post "ask_approve", to: "tops#ask_approve"
  get "update_grade", to: "tops#update_grade"
  get "chats/new/:teacher_id", to: "chats#new"

  # Defines the root path route ("/")
  # root "articles#index"
  root 'tops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/arium.rb
class Arium < ApplicationRecord
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :teacher

end

app/models/flow.rb
class Flow < ApplicationRecord

  belongs_to :main

end

app/models/homework.rb
class Homework < ApplicationRecord

  validates :main_id, uniqueness: { scope: :textbook_id }

  belongs_to :main
  belongs_to :textbook, class_name: "Testbook"

end

app/models/main.rb
class Main < ApplicationRecord

  belongs_to :student

  has_many :flows, dependent: :destroy
  accepts_nested_attributes_for :flows, reject_if: proc {|attributes| attributes['content'].blank?}, allow_destroy: true
  
  has_many :main_textbooks, dependent: :destroy
  accepts_nested_attributes_for :main_textbooks, reject_if: proc {|attributes| attributes['textbook_id'].blank?}, allow_destroy: true

  has_many :homeworks, dependent: :destroy
  accepts_nested_attributes_for :homeworks, reject_if: proc {|attributes| attributes['textbook_id'].blank?}, allow_destroy: true

  def textbooks_hash
    ret = {}
    self.main_textbooks.each do |mt|
      t = Testbook.find_by(id: mt.textbook_id)
      ret[t.id] = {id: mt.id, name: t.name, finished_place: mt.finished_place} if t
    end
    return ret
  end
  
  def homeworks_hash
    ret = {}
    self.homeworks.each do |h|
      t = Testbook.find_by(id: h.textbook_id)
      ret[t.id] = {id: h.id, name: t.name, amount: h.amount} if t
    end
    return ret
  end

  def student
    unless self.student_id.blank?
      return Student.find(self.student_id)
    else
      return Student.find(session[:student_id]) if session[:student_id]
    end
    return nil
  end

  def textbook_ids
    arr = []
    self.main_textbooks.each do |mt|
      arr.push(mt.textbook_id)
    end
    return arr
  end

  def homework_ids
    arr = []
    self.homeworks.each do |h|
      arr.push(h.textbook_id)
    end
    return arr
  end

end

app/models/main_textbook.rb
class MainTextbook < ApplicationRecord

  validates :main_id, uniqueness: { scope: :textbook_id }

  belongs_to :main
  belongs_to :textbook, class_name: "Testbook"

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

  def hash_format
    return {id: self.id, name: self.name}
  end
  
end

app/models/school.rb
class School < ApplicationRecord
  
  validates :name, presence: :true
  validates :school_id, presence: :true
  validates :prefecture_id, presence: :true
  validates :name, uniqueness: true
  validates :school_id, uniqueness: :true

  def hash_format
    return {id: self.id, name: self.name}
  end
  
end

app/models/student.rb
class Student < ApplicationRecord

  validates :level, presence: :true
  validates :attitude, presence: :true
  has_many :mains, -> { order(updated_at: :desc) }

  def area
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    a = Arium.find_by(id: p.area_id) if p
    return a.id if a
  end

  def prefecture
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    return p.id if p
  end

  def school
    return School.find_by(id: self.school_id)
  end

end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :chats

  def area
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    a = Arium.find_by(id: p.area_id) if p
    return a.id if a
  end

  def prefecture
    p = Prefecture.find_by(id: self.school.prefecture_id) if self.school
    return p.id if p
  end

  def school
    return School.find_by(id: self.school_id)
  end

  def hash_format
    if self.school.blank?
      return {id: self.id, name: self.name, school: ""}
    else
      return {id: self.id, name: self.name, school: self.school.name}
    end
  end

end

app/models/testbook.rb
class Testbook < ApplicationRecord
  validates :name, uniqueness: true
  validates :name_kana, presence: :true
end

app/helpers/aria_helper.rb
module AriaHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/mains_helper.rb
module MainsHelper

  def subjects_options
    return {"国語" => 1, "算数・数学" => 2, "理科" => 3, "社会" => 4, "英語" => 5}
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper

  def grades_options
    options = {}
    (1..6).each do |n|
      options = options.merge({"小学#{n}年" => n})
    end
    (7..9).each do |n|
      options = options.merge({"中学#{n-6}年" => n})
    end
    (10..12).each do |n|
      options = options.merge({"高校#{n-9}年" => n})
    end
    options = options.merge({"既卒" => 13})
    return options
  end

  def levels_options
    return {"かなり前の内容から復習が必要" => 1, "復習が必要" => 2, "学校の授業に合わせたらいい" => 3, "少し予習も取り入れている" => 4}
  end
  
  def attitudes_options
    return {"全然集中しない" => 1, "やる気にムラがある" => 2, "いつも集中している" => 3}
  end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/testbooks_helper.rb
module TestbooksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TRY 引継ぎシステム</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script>
      (function ($) {
        $.fn.autoKana = function (element1, element2, passedOptions) {

          var options = $.extend(
            {
              'katakana': false
            }, passedOptions);

          var kana_extraction_pattern = new RegExp('[^ 　ぁあ-んー]', 'g');
          var kana_compacting_pattern = new RegExp('[ぁぃぅぇぉっゃゅょ]', 'g');
          var elName,
            elKana,
            active = false,
            timer = null,
            flagConvert = true,
            input,
            values,
            ignoreString,
            baseKana;

          elName = $(element1);
          elKana = $(element2);
          active = true;
          _stateClear();

          elName.blur(_eventBlur);
          elName.focus(_eventFocus);
          elName.keydown(_eventKeyDown);

          function start() {
            active = true;
          };

          function stop() {
            active = false;
          };

          function toggle(event) {
            var ev = event || window.event;
            if (event) {
              var el = Event.element(event);
              if (el.checked) {
                active = true;
              } else {
                active = false;
              }
            } else {
              active = !active;
            }
          };

          function _checkConvert(new_values) {
            if (!flagConvert) {
              if (Math.abs(values.length - new_values.length) > 1) {
                var tmp_values = new_values.join('').replace(kana_compacting_pattern, '').split('');
                if (Math.abs(values.length - tmp_values.length) > 1) {
                  _stateConvert();
                }
              } else {
                if (values.length == input.length && values.join('') != input) {
                  if (input.match(kana_extraction_pattern)) {
                    _stateConvert();
                  }
                }
              }
            }
          };

          function _checkValue() {
              var new_input, new_values;
              new_input = elName.val()
              if (new_input == '' && elKana.val() != '') {
                _stateClear();
                _setKana();
              } else {
                new_input = _removeString(new_input);
                if (input == new_input) {
                  return;
                } else {
                  input = new_input;
                  if (!flagConvert) {
                    new_values = new_input.replace(kana_extraction_pattern, '').split('');
                    _checkConvert(new_values);
                    _setKana(new_values);
                  }
                }
              }
          };

          function _clearInterval() {
            clearInterval(timer);
          };

          function _eventBlur(event) {
            _clearInterval();
          };
          function _eventFocus(event) {
            _stateInput();
            _setInterval();
          };
          function _eventKeyDown(event) {
            if (flagConvert) {
              _stateInput();
            }
          };
          function _isHiragana(chara) {
            return ((chara >= 12353 && chara <= 12435) || chara == 12445 || chara == 12446);
          };
          function _removeString(new_input) {
            if (new_input.indexOf(ignoreString) !== -1) {
              return new_input.replace(ignoreString, '');
            } else {
              var i, ignoreArray, inputArray;
              ignoreArray = ignoreString.split('');
              inputArray = new_input.split('');
              for (i = 0; i < ignoreArray.length; i++) {
                if (ignoreArray[i] == inputArray[i]) {
                  inputArray[i] = '';
                }
              }
              return inputArray.join('');
            }
          };
          function _setInterval() {
            var self = this;
            timer = setInterval(_checkValue, 30);
          };
          function _setKana(new_values) {
            if (!flagConvert) {
              if (new_values) {
                values = new_values;
              }
              if (active) {
                var _val = _toKatakana(baseKana + values.join(''));
                elKana.val(_val).change();
              }
            }
          };
          function _stateClear() {
            baseKana = '';
            flagConvert = false;
            ignoreString = '';
            input = '';
            values = [];
          };
          function _stateInput() {
            baseKana = elKana.val();
            flagConvert = false;
            ignoreString = elName.val();
          };
          function _stateConvert() {
            baseKana = baseKana + values.join('');
            flagConvert = true;
            values = [];
          };
          function _toKatakana(src) {
            if (options.katakana) {
              var c, i, str;
              str = new String;
              for (i = 0; i < src.length; i++) {
                c = src.charCodeAt(i);
                if (_isHiragana(c)) {
                  str += String.fromCharCode(c + 96);
                } else {
                  str += src.charAt(i);
                }
              }
              return str;
            } else {
              return src;
            }
          }
        };
      })(jQuery);

      function setCSRFtoken() {
        $.ajaxPrefilter(function (options, originalOptions, jqXHR) {
          if (!options.crossDomain) {
            const token = $('meta[name="csrf-token"]').attr('content');
            if (token) {
              return jqXHR.setRequestHeader('X-CSRF-Token', token);
            }
          }
        });
      }
    </script>
  </head>

  <body>
    <div class="no-print">
      <% if current_teacher %>
        <div style="display: flex;">
          <%= button_to 'Sign Out', destroy_teacher_session_path, method: :delete %>　<%= link_to current_teacher.email, "#{teachers_path}/#{current_teacher.id}" unless controller_name == "teachers" && action_name == "show" && params[:id] == current_teacher.id.to_s %>
        </div>
        
        <% if current_teacher.is_authenticated %>
          <%= link_to 'Topへ', root_path if controller_name == "students" && action_name == "index" %>
          <%= link_to '生徒一覧ページへ', students_path unless (controller_name == "students" || controller_name == "tops") && action_name == "index" %>
        <% else %>
          <%= link_to 'Topへ', root_path unless controller_name == "tops" && action_name == "index" %>
        <% end %>
      <% else %>
        <%= link_to 'Topへ', root_path unless controller_name == "tops" && action_name == "index" %>
      <% end %>
    </div>
    <%= yield %>
    <div class="no-print">
      <% unless controller_name == "chats" %>
        <% if teacher_signed_in? %>
          
          <% if current_teacher.id == 1 %>
            <%= link_to '教師一覧', teachers_path %>
          <% else %>
            <%= link_to '困ったときはこちら', chats_path %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </body>
</html>